/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaDatos.M_Usuario;
import CapaLogica.N_Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MATIAS
 */
public class FrmLogin extends javax.swing.JFrame {

    int cont, xMouse, yMouse;

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        jScrollPane3.setVisible(false);
        setLocationRelativeTo(null); //lo que hacemos es que el formulario inicie en el centro de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblpassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        checmostrar = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablalistado = new javax.swing.JTable();
        btnlogin = new javax.swing.JPanel();
        txtlogin = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        logoname = new javax.swing.JLabel();
        citybg = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnsalir = new javax.swing.JPanel();
        txtsalir = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/usuario.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 149, 144));

        lblUsuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("USUARIO:");
        bg.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(204, 204, 204));
        txtusuario.setText("Ingrese su Usuario");
        txtusuario.setBorder(null);
        txtusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtusuarioMousePressed(evt);
            }
        });
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        bg.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 370, 30));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 380, 10));

        lblpassword.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(0, 0, 0));
        lblpassword.setText("CONTRASEÑA:");
        bg.add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        txtpassword.setBackground(new java.awt.Color(255, 255, 255));
        txtpassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(204, 204, 204));
        txtpassword.setText("********");
        txtpassword.setBorder(null);
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpasswordMousePressed(evt);
            }
        });
        bg.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 380, 30));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 380, 10));

        checmostrar.setBackground(new java.awt.Color(255, 255, 255));
        checmostrar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        checmostrar.setText("Mostrar Contraseña");
        checmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checmostrarActionPerformed(evt);
            }
        });
        bg.add(checmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablalistado);

        bg.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 10, 13));

        btnlogin.setBackground(new java.awt.Color(0, 102, 153));

        txtlogin.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtlogin.setForeground(new java.awt.Color(255, 255, 255));
        txtlogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtlogin.setText("INGRESAR");
        txtlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtloginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnloginLayout = new javax.swing.GroupLayout(btnlogin);
        btnlogin.setLayout(btnloginLayout);
        btnloginLayout.setHorizontalGroup(
            btnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtlogin, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnloginLayout.setVerticalGroup(
            btnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtlogin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 140, 50));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/logo.png"))); // NOI18N
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 290, 160));

        logoname.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        logoname.setForeground(new java.awt.Color(255, 255, 255));
        logoname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoname.setText("NOMBRE EMPRESA");
        bg.add(logoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 290, 30));

        citybg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/city.png"))); // NOI18N
        bg.add(citybg, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 0, -1, 500));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnsalir.setBackground(new java.awt.Color(255, 255, 255));

        txtsalir.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txtsalir.setForeground(new java.awt.Color(0, 0, 0));
        txtsalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtsalir.setText("X");
        txtsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtsalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtsalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnsalirLayout = new javax.swing.GroupLayout(btnsalir);
        btnsalir.setLayout(btnsalirLayout);
        btnsalirLayout.setHorizontalGroup(
            btnsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtsalir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnsalirLayout.setVerticalGroup(
            btnsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtsalir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 740, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/favicon.png"))); // NOI18N
        jLabel4.setText("LOGO");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 50));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("INICIAR SESIÓN");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        txtusuario.transferFocus(); //para que regrese el cursor
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void checmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checmostrarActionPerformed
        if (checmostrar.isSelected()) {//si está seleccionado
            txtpassword.setEchoChar((char) 0); //muestra los datos

        } else {
            txtpassword.setEchoChar('*'); //sino se intercambian los caracteres por asteriscos

        }
    }//GEN-LAST:event_checmostrarActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX(); //Obtenemos la posición del mouse en el programa, en el eje x 
        yMouse = evt.getY(); //Obtenemos la posición del mouse en el programa, en el eje y 
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen(); //obtiene la posición del mouse en la pantalla del eje x
        int y = evt.getYOnScreen(); //obtiene la posición del mouse en la pantalla del eje y
        this.setLocation(x - xMouse, y - yMouse); //cuando la ventana es arrastrada lo que se debe hacer es establecer la localización de la ventana
    }//GEN-LAST:event_headerMouseDragged

    private void txtsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsalirMouseClicked
        dispose(); //ordenamos que cuando se presione el boton que contiene la X este cierre el programa
    }//GEN-LAST:event_txtsalirMouseClicked

    private void txtsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsalirMouseEntered
        btnsalir.setBackground(Color.red); //cambiamos el color de fondo cuando el mouse se posiciona sobre el boton
        txtsalir.setForeground(Color.white); //cambiamos el color de letra cuando el mouse se posiciona sobre el boton
    }//GEN-LAST:event_txtsalirMouseEntered

    private void txtsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsalirMouseExited
        btnsalir.setBackground(Color.white); //cambiamos el color de fondo cuando el mouse se retira sobre el boton
        txtsalir.setForeground(Color.black); //cambiamos el color de letra cuando el mouse se retira sobre el boton
    }//GEN-LAST:event_txtsalirMouseExited

    private void txtloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtloginMouseClicked
        try {
            DefaultTableModel modelo;
            N_Usuario func = new N_Usuario();
            M_Usuario dts = new M_Usuario();

            //envio usuario y pass 
            dts.setUsuario(txtusuario.getText());
            dts.setPassword(txtpassword.getText());

            modelo = func.logeo(dts.getUsuario(), dts.getPassword());
            tablalistado.setModel(modelo);

            if (func.totalregistros > 0) {
                cont++;
                this.dispose();

                FrmMenu form = new FrmMenu(); //creamos un objeto del formulario menú
                form.toFront(); //trae al frente al formulario menú
                form.setVisible(true); //lo hace visible

                //extraemos de la tabla los datos de id,nombre y apellido
                FrmMenu.lblidUsuario.setText(tablalistado.getValueAt(0, 0).toString());
                FrmMenu.lblnombre.setText(tablalistado.getValueAt(0, 2).toString());
                FrmMenu.lblapellidos.setText(tablalistado.getValueAt(0, 3).toString());

            } else {
                JOptionPane.showMessageDialog(rootPane, "Acceso Denegado", "Acceso al Sistema", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtloginMouseClicked

    private void txtloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtloginMouseEntered
        btnlogin.setBackground(new Color(2, 134, 201)); //cambiamos el color de fondo cuando el mouse se posiciona sobre el boton
    }//GEN-LAST:event_txtloginMouseEntered

    private void txtloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtloginMouseExited
        btnlogin.setBackground(new Color(0, 102, 153)); //cambiamos el color de fondo cuando el mouse se retira sobre el boton
    }//GEN-LAST:event_txtloginMouseExited

    private void txtusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusuarioMousePressed
        if (txtusuario.getText().equals("Ingrese su Usuario")) {
            txtusuario.setText(""); //borramos el texto boton es presinonado
            txtusuario.setForeground(Color.black); //cambiamos el color de letra cuando el mouse se retira sobre el boton
        }
        if (String.valueOf(txtpassword.getPassword()).isEmpty()) {
            txtpassword.setText("********"); //cambiamos el texto por * cuando el boton es presinonado
            txtpassword.setForeground(new Color(204,204,204)); //cambiamos el color de letra cuando el mouse se retira sobre el boton
        }
    }//GEN-LAST:event_txtusuarioMousePressed

    private void txtpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMousePressed
        if (String.valueOf(txtpassword.getPassword()).equals("********")) {
            txtpassword.setText(""); //borramos el texto boton es presinonado
            txtpassword.setForeground(Color.black); //cambiamos el color de letra cuando el mouse se retira sobre el boton
        }
        if (txtusuario.getText().isEmpty()) {
            txtusuario.setText("Ingrese su Usuario"); //cambiamos el texto por * cuando el boton es presinonado
            txtusuario.setForeground(new Color(204,204,204)); //cambiamos el color de letra cuando el mouse se retira sobre el boton
        }
    }//GEN-LAST:event_txtpasswordMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnlogin;
    private javax.swing.JPanel btnsalir;
    private javax.swing.JCheckBox checmostrar;
    private javax.swing.JLabel citybg;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoname;
    private javax.swing.JTable tablalistado;
    private javax.swing.JLabel txtlogin;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JLabel txtsalir;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
